# Generated by Django 4.2.7 on 2025-11-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Default', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('vendor', 'Vendor'), ('delivery', 'Delivery'), ('doctor', 'Doctor'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
