# Generated by Django 4.2.7 on 2025-11-25 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import vendorapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=80)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('items', models.JSONField(default=list)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_type', models.CharField(default='home', max_length=50)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('picked', 'Picked'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('prescription_required', models.BooleanField(default=False)),
                ('cancelled_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-order_time'],
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('pharmacy_name', models.CharField(blank=True, max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=vendorapp.models.vendor_image_path)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(blank=True, max_length=200)),
                ('uploaded_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='prescriptions/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='vendorapp.vendororder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='vendorapp.vendorprofile')),
            ],
            options={
                'ordering': ['-uploaded_time'],
            },
        ),
        migrations.AddField(
            model_name='vendororder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='vendorapp.vendorprofile'),
        ),
        migrations.CreateModel(
            name='VendorMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('min_stock', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('prescription_required', models.BooleanField(default=False)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('batch_no', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='vendorapp.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('vendor', 'name', 'batch_no')},
            },
        ),
    ]
