# Generated by Django 4.2.7 on 2025-11-25 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendormedicine',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vendororder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vendorprescription',
            options={},
        ),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='joined_date',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='vendormedicine',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vendororder',
            name='cancelled_time',
        ),
        migrations.RemoveField(
            model_name='vendorprescription',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='vendorprescription',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='rating',
        ),
        migrations.AddField(
            model_name='vendormedicine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendorprescription',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprescription',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprescription',
            name='medicines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vendormedicine',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendormedicine',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vendormedicine',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vendormedicine',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorprescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_prescriptions/'),
        ),
        migrations.AlterField(
            model_name='vendorprescription',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='pharmacy_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
