# Generated by Django 4.2.7 on 2025-11-24 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('current_location', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_type', models.CharField(choices=[('Motorcycle', 'Motorcycle'), ('Scooter', 'Scooter'), ('Bicycle', 'Bicycle'), ('Car', 'Car')], default='Motorcycle', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('completion_rate', models.CharField(default='0%', max_length=20)),
                ('response_time', models.CharField(blank=True, default='—', max_length=50)),
                ('average_rating', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
